#!/usr/bin/env node
/**
 * Generate manual/TEST-CASES.xlsx from the in-script test plan rows.
 * Run via: node manual/generate-xlsx.mjs
 *
 * Uses ExcelJS — install with `npm i -D exceljs` inside e2e/ if missing,
 * or run from a node_modules root that has it.
 *
 * The xlsx is the source-of-truth contract per autoqa conventions.
 * TEST_CASES.md is the human-readable pointer; regenerate both when rows change.
 */
import ExcelJS from 'exceljs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const HEADERS = [
  'Test ID', 'Feature', 'Test Title', 'Description', 'Pre-conditions',
  'Test Data', 'Steps', 'Expected Result', 'Severity', 'Priority',
  'Status', 'Case Type', 'Execution Date', 'Executed By', 'Spec File', 'Notes',
];

// Default specs (used when a row omits its explicit `spec` field). Rows for
// new feature areas — Dashboard, Ticket Detail, New Ticket, Org Settings,
// Manage Account, Navigation, and the Tickets API — set their `spec` field
// explicitly so the workbook stays accurate even as the suite grows.
const E2E_SPEC = 'e2e/tests/signin.spec.ts';
const API_SPEC = 'api/tests/signin.spec.ts';
const TODAY = new Date().toISOString().slice(0, 10);
const E2E_TICKETS_API_SPEC = 'api/tests/tickets.spec.ts';

const rows = [
  {
    id: 'SI0011', feature: 'Sign-in',
    title: 'User sees all core sign-in elements on page load',
    description: 'Confirms the sign-in page renders every interactive control before the user attempts auth.',
    pre: 'Anonymous; no session cookies.',
    data: 'None (static page).',
    steps: '1. Navigate to /sign-in.\n2. Assert email/password fields, Log-in button, "Forgot password?", "Sign up", "Continue with Email", "Continue with Google" are all visible.',
    expected: 'All seven core elements visible on the form.',
    severity: 'Critical', priority: 'P0', status: 'Pass', caseType: 'Happy Path',
  },
  {
    id: 'SI0002', feature: 'Sign-in',
    title: 'User sees validation error when submitting an empty form',
    description: 'Client-side validation must block submission when no email is entered.',
    pre: 'On /sign-in.',
    data: 'Empty form.',
    steps: '1. Click "Log in" without filling fields.\n2. Assert "Invalid email" error visible and URL still /sign-in.',
    expected: '"Invalid email" inline error visible; URL unchanged.',
    severity: 'Major', priority: 'P1', status: 'Pass', caseType: 'Negative',
  },
  {
    id: 'SI0003', feature: 'Sign-in',
    title: 'User sees validation error for an invalid email format',
    description: 'Email-format regex must reject malformed input before the auth call.',
    pre: 'On /sign-in.',
    data: 'Credentials.invalidFormatEmail = "notanemail"; Credentials.arbitraryPassword.',
    steps: '1. Fill email with malformed value.\n2. Fill any password.\n3. Submit.\n4. Assert "Invalid email" error visible; URL unchanged.',
    expected: '"Invalid email" inline error visible.',
    severity: 'Major', priority: 'P1', status: 'Pass', caseType: 'Validation',
  },
  {
    id: 'SI0006', feature: 'Sign-in',
    title: 'User cannot log in with email only and no password',
    description: 'Password is required; submission with only email must not authenticate.',
    pre: 'On /sign-in.',
    data: 'Credentials.valid.email; password empty.',
    steps: '1. Fill email only.\n2. Submit.\n3. Assert URL still /sign-in; email field still visible.',
    expected: 'URL unchanged; form remains.',
    severity: 'Major', priority: 'P1', status: 'Pass', caseType: 'Negative',
  },
  {
    id: 'SI0007', feature: 'Sign-in',
    title: 'User can toggle password field visibility',
    description: 'Visibility toggle flips the password input between masked and plain text.',
    pre: 'On /sign-in.',
    data: 'Credentials.arbitraryPassword.',
    steps: '1. Fill password.\n2. Assert input type=password.\n3. Click toggle. Assert type=text.\n4. Click toggle again. Assert type=password.',
    expected: 'type attribute flips on each toggle click.',
    severity: 'Minor', priority: 'P2', status: 'Pass', caseType: 'Happy Path',
  },
  {
    id: 'SI0008', feature: 'Sign-in',
    title: 'User navigates to the reset-password page via "Forgot password?"',
    description: '"Forgot password?" link routes to /reset-password.',
    pre: 'On /sign-in.', data: 'None.',
    steps: '1. Click "Forgot password?".\n2. Wait for URL to contain /reset-password.',
    expected: 'URL ends with /reset-password.',
    severity: 'Minor', priority: 'P2', status: 'Pass', caseType: 'Happy Path',
  },
  {
    id: 'SI0009', feature: 'Sign-in',
    title: 'User navigates to the sign-up page via the "Sign up" link',
    description: '"Sign up" link routes to /sign-up.',
    pre: 'On /sign-in.', data: 'None.',
    steps: '1. Click "Sign up" inside footer paragraph.\n2. Wait for URL to contain /sign-up.',
    expected: 'URL ends with /sign-up.',
    severity: 'Minor', priority: 'P2', status: 'Pass', caseType: 'Happy Path',
  },
  {
    id: 'SI0010', feature: 'Sign-in',
    title: 'User navigates to the email-OTP page via "Continue with Email"',
    description: 'Alt-auth link routes to /email-otp.',
    pre: 'On /sign-in.', data: 'None.',
    steps: '1. Click "Continue with Email".\n2. Wait for URL to contain /email-otp.',
    expected: 'URL ends with /email-otp.',
    severity: 'Minor', priority: 'P2', status: 'Pass', caseType: 'Happy Path',
  },
  {
    id: 'SI0001', feature: 'Sign-in',
    title: 'User logs in successfully with valid credentials',
    description: 'Happy-path auth: valid email+password lands on /onboarding with welcome banner.',
    pre: 'Anonymous; cookies cleared.',
    data: 'Credentials.valid.email + Credentials.valid.password (env-driven).',
    steps: '1. Submit valid credentials.\n2. Wait for /onboarding.\n3. Assert "Welcome to Demo SaaS" visible.',
    expected: 'URL ends /onboarding; welcome text visible.',
    severity: 'Blocker', priority: 'P0', status: 'Pass', caseType: 'Happy Path',
  },
  {
    id: 'SI0004', feature: 'Sign-in',
    title: 'User sees auth error when password is wrong',
    description: 'Backend rejects valid email + wrong password.',
    pre: 'Anonymous; cookies cleared.',
    data: 'Credentials.valid.email + Credentials.wrongPassword.',
    steps: '1. Submit valid email + wrong password.\n2. Assert rejection error visible (credential error OR rate-limit notice).\n3. Assert URL still /sign-in.',
    expected: 'Rejection message visible; user not authenticated.',
    severity: 'Critical', priority: 'P0', status: 'Pass', caseType: 'Negative',
  },
  {
    id: 'SI0005', feature: 'Sign-in',
    title: 'User sees auth error when email is not registered',
    description: 'Backend rejects unregistered email gracefully.',
    pre: 'Anonymous; cookies cleared.',
    data: 'Credentials.unregisteredEmail + Credentials.arbitraryPassword.',
    steps: '1. Submit unregistered email + any password.\n2. Assert rejection error visible.\n3. Assert URL still /sign-in.',
    expected: 'Rejection message visible; user not authenticated.',
    severity: 'Major', priority: 'P1', status: 'Pass', caseType: 'Negative',
  },
  // ---------- API tests (api/tests/signin.spec.ts) ----------
  {
    id: 'AS0001', feature: 'Sign-in API', spec: API_SPEC,
    title: 'Valid credentials return 200 with user object',
    description: 'Happy path: POST /api/auth/sign-in/email with real credentials returns 200 + user object.',
    pre: 'Network reachable; SIGNIN_EMAIL/SIGNIN_PASSWORD env vars set.',
    data: 'Credentials.valid.email + Credentials.valid.password.',
    steps: '1. POST endpoint with valid body.\n2. Assert HTTP 200.\n3. Assert body.user.email matches Credentials.valid.email and body.user.emailVerified is true.',
    expected: 'HTTP 200; body.user.email = expected; emailVerified = true.',
    severity: 'Blocker', priority: 'P0', status: 'Pass', caseType: 'Happy Path',
  },
  {
    id: 'AS0002', feature: 'Sign-in API', spec: API_SPEC,
    title: 'Wrong password returns 401 INVALID_EMAIL_OR_PASSWORD',
    description: 'Auth API rejects valid email + wrong password.',
    pre: 'Network reachable.',
    data: 'Credentials.valid.email + Credentials.wrongPassword.',
    steps: '1. POST endpoint.\n2. Assert HTTP 401.\n3. Assert body.code = "INVALID_EMAIL_OR_PASSWORD".',
    expected: '401 with documented error code.',
    severity: 'Critical', priority: 'P0', status: 'Pass', caseType: 'Negative',
  },
  {
    id: 'AS0003', feature: 'Sign-in API', spec: API_SPEC,
    title: 'Unregistered email returns 401 INVALID_EMAIL_OR_PASSWORD',
    description: 'Auth API rejects unregistered email with same error code as wrong password (no enumeration).',
    pre: 'Network reachable.',
    data: 'Credentials.unregisteredEmail + Credentials.arbitraryPassword.',
    steps: '1. POST endpoint.\n2. Assert HTTP 401.\n3. Assert body.code = "INVALID_EMAIL_OR_PASSWORD".',
    expected: '401 with same error code as wrong-password (no enumeration leak).',
    severity: 'Major', priority: 'P1', status: 'Pass', caseType: 'Negative',
  },
  {
    id: 'AS0004', feature: 'Sign-in API', spec: API_SPEC,
    title: 'Malformed email returns 400 INVALID_EMAIL',
    description: 'Server-side regex rejects malformed email before auth lookup.',
    pre: 'Network reachable.',
    data: 'Credentials.invalidFormatEmail + Credentials.arbitraryPassword.',
    steps: '1. POST endpoint.\n2. Assert HTTP 400.\n3. Assert body.code = "INVALID_EMAIL".',
    expected: '400 with code = "INVALID_EMAIL".',
    severity: 'Major', priority: 'P1', status: 'Pass', caseType: 'Validation',
  },
  {
    id: 'AS0005', feature: 'Sign-in API', spec: API_SPEC,
    title: 'Missing email field returns 400 with zod details',
    description: 'Schema validation flags missing `email` field with zod-style details array.',
    pre: 'Network reachable.',
    data: '{ password: Credentials.arbitraryPassword }.',
    steps: '1. POST endpoint with body missing `email`.\n2. Assert HTTP 400.\n3. Assert body.details contains an entry with path ["email"].',
    expected: '400 with details array including email path.',
    severity: 'Major', priority: 'P1', status: 'Pass', caseType: 'Validation',
  },
  {
    id: 'AS0006', feature: 'Sign-in API', spec: API_SPEC,
    title: 'Missing password field returns 400 with zod details',
    description: 'Schema validation flags missing `password` field with zod-style details array.',
    pre: 'Network reachable.',
    data: '{ email: Credentials.valid.email }.',
    steps: '1. POST endpoint with body missing `password`.\n2. Assert HTTP 400.\n3. Assert body.details contains an entry with path ["password"].',
    expected: '400 with details array including password path.',
    severity: 'Major', priority: 'P1', status: 'Pass', caseType: 'Validation',
  },
  {
    id: 'AS0007', feature: 'Sign-in API', spec: API_SPEC,
    title: 'Empty JSON body returns 400 with zod details',
    description: 'Both required keys missing surface in zod-style details array.',
    pre: 'Network reachable.',
    data: '{}.',
    steps: '1. POST endpoint with empty JSON body.\n2. Assert HTTP 400.\n3. Assert body.details paths include "email" and "password".',
    expected: '400 with details paths covering both required fields.',
    severity: 'Major', priority: 'P1', status: 'Pass', caseType: 'Validation',
  },
  // ---------- Dashboard (e2e/tests/dashboard.spec.ts) ----------
  {
    id: 'DB0001', feature: 'Dashboard', spec: 'e2e/tests/dashboard.spec.ts',
    title: 'User lands on /<slug>/tickets with all core chrome visible',
    description: 'Post-login default landing — tickets list page must render search, filter, New button, and header avatar.',
    pre: 'Signed in with at least one organization (storage state from globalSetup).',
    data: 'org slug captured during globalSetup.',
    steps: '1. Navigate to /<slug>/tickets.\n2. Assert search, status filter, New link, user-menu trigger, org switcher all visible.\n3. Assert URL ends with /<slug>/tickets.',
    expected: 'All five chrome elements visible; URL matches.',
    severity: 'Critical', priority: 'P0', status: 'Pass', caseType: 'Happy Path',
  },
  {
    id: 'DB0002', feature: 'Dashboard', spec: 'e2e/tests/dashboard.spec.ts',
    title: 'Header has Tickets and Settings tabs, Tickets is active by default',
    description: 'Confirms tab routing structure and default selection.',
    pre: 'On /<slug>/tickets.', data: 'None.',
    steps: '1. Assert both header tabs visible.\n2. Assert aria-selected=true on Tickets tab.',
    expected: 'Two tabs present; Tickets selected.',
    severity: 'Minor', priority: 'P2', status: 'Pass', caseType: 'UI and validation',
  },
  {
    id: 'DB0003', feature: 'Dashboard', spec: 'e2e/tests/dashboard.spec.ts',
    title: 'Sidebar nav exposes Tickets, Organization settings, Manage account, Sign out',
    description: 'Sidebar NavLinks must always be visible while signed in.',
    pre: 'On /<slug>/tickets.', data: 'None.',
    steps: '1. Assert each of the four NavLinks visible by text inside <nav>.',
    expected: 'All four NavLinks present.',
    severity: 'Minor', priority: 'P2', status: 'Pass', caseType: 'UI and validation',
  },
  {
    id: 'DB0004', feature: 'Dashboard', spec: 'e2e/tests/dashboard.spec.ts',
    title: 'Seeded sample tickets are findable in the org\'s ticket list',
    description: 'After "Import example tickets", the seed row "Session timeout not working correctly" must be findable via search regardless of how many newer tickets E2E runs have added.',
    pre: 'Org was bootstrapped with the sample-tickets import.',
    data: 'Seed title: "Session timeout not working correctly".',
    steps: '1. Search the table for the seeded title.\n2. Assert the row is rendered.',
    expected: 'Seeded row visible after search.',
    severity: 'Major', priority: 'P1', status: 'Pass', caseType: 'Happy Path',
  },
  {
    id: 'DB0005', feature: 'Dashboard', spec: 'e2e/tests/dashboard.spec.ts',
    title: 'Clicking "Settings" header tab routes to /<slug>/settings',
    description: 'Header tab routing works for Settings.',
    pre: 'On /<slug>/tickets.', data: 'None.',
    steps: '1. Click Settings tab.\n2. Wait for URL change.',
    expected: 'URL ends /<slug>/settings.',
    severity: 'Minor', priority: 'P2', status: 'Pass', caseType: 'Navigation',
  },
  {
    id: 'DB0006', feature: 'Dashboard', spec: 'e2e/tests/dashboard.spec.ts',
    title: 'Clicking "New" routes to /<slug>/tickets/new',
    description: 'Authenticated user can navigate to the new-ticket form.',
    pre: 'On /<slug>/tickets.', data: 'None.',
    steps: '1. Click "New" link.\n2. Wait for URL change.',
    expected: 'URL ends /<slug>/tickets/new.',
    severity: 'Minor', priority: 'P2', status: 'Pass', caseType: 'Navigation',
  },
  {
    id: 'DB0007', feature: 'Dashboard', spec: 'e2e/tests/dashboard.spec.ts',
    title: 'Search by title puts the term in ?search and narrows the table',
    description: 'Search input + Enter triggers a tRPC refetch with the new search param; URL gains ?search=...',
    pre: 'On /<slug>/tickets.', data: 'Search term: "Session timeout" (matches exactly one seed row).',
    steps: '1. Type term in search input.\n2. Press Enter.\n3. Wait for tickets.getList response.\n4. Assert URL contains search param.\n5. Assert exactly 1 row visible.',
    expected: '?search=Session+timeout in URL; 1 row in table.',
    severity: 'Major', priority: 'P1', status: 'Pass', caseType: 'Happy Path',
  },
  {
    id: 'DB0008', feature: 'Dashboard', spec: 'e2e/tests/dashboard.spec.ts',
    title: 'Search with a guaranteed-unique gibberish term yields zero rows',
    description: 'Empty-results state — search that matches nothing must render no ticket rows.',
    pre: 'On /<slug>/tickets.', data: 'Search term: "zzzz_no_such_ticket_9921".',
    steps: '1. Search gibberish term.\n2. Assert URL contains search param.\n3. Assert 0 rows.',
    expected: '0 rows.',
    severity: 'Minor', priority: 'P2', status: 'Pass', caseType: 'Negative',
  },
  {
    id: 'DB0009', feature: 'Dashboard', spec: 'e2e/tests/dashboard.spec.ts',
    title: 'Status filter "In Progress" sets ?status=InProgress and shows only matching rows',
    description: 'Status filter narrows the table to rows matching the chosen status.',
    pre: 'On /<slug>/tickets.', data: 'Filter value: "In Progress".',
    steps: '1. Open status filter.\n2. Pick "In Progress".\n3. Assert URL contains ?status=InProgress.\n4. Assert every visible status badge reads "In Progress".',
    expected: '?status=InProgress; all badges match.',
    severity: 'Major', priority: 'P1', status: 'Pass', caseType: 'Filtering',
  },
  {
    id: 'DB0010', feature: 'Dashboard', spec: 'e2e/tests/dashboard.spec.ts',
    title: 'Reverting the status filter to "Any" clears ?status from the URL',
    description: 'Picking "Any" must remove the status URL param entirely.',
    pre: 'On /<slug>/tickets with status filter active.', data: 'Filter value: "Any".',
    steps: '1. Pick "In Progress".\n2. Pick "Any".\n3. Assert URL has no ?status param.',
    expected: 'No ?status= in URL.',
    severity: 'Minor', priority: 'P2', status: 'Pass', caseType: 'Filtering',
  },
  // ---------- Ticket Detail (e2e/tests/ticketDetail.spec.ts) ----------
  {
    id: 'TK0001', feature: 'Ticket Detail', spec: 'e2e/tests/ticketDetail.spec.ts',
    title: 'Clicking a ticket row opens the detail dialog with all core fields',
    description: 'The dialog must render title, status combobox, description, ID, reporter, created date, and Comments section.',
    pre: 'On /<slug>/tickets with the seed row searchable.',
    data: 'Seed title "Session timeout not working correctly".',
    steps: '1. Search for the seed title.\n2. Click the row.\n3. Assert dialog open.\n4. Assert title + every core field visible.',
    expected: 'Dialog renders all six core fields.',
    severity: 'Critical', priority: 'P0', status: 'Pass', caseType: 'Happy Path',
  },
  {
    id: 'TK0002', feature: 'Ticket Detail', spec: 'e2e/tests/ticketDetail.spec.ts',
    title: 'URL gains ?selectedId=<id> while the dialog is open',
    description: 'The dialog open state is reflected in the URL via ?selectedId so the page is deep-linkable.',
    pre: 'Dialog open via row click.', data: 'None.',
    steps: '1. Assert ?selectedId in URL matches a ticket id ([a-z0-9]+).',
    expected: 'selectedId search param present.',
    severity: 'Minor', priority: 'P2', status: 'Pass', caseType: 'Navigation',
  },
  {
    id: 'TK0003', feature: 'Ticket Detail', spec: 'e2e/tests/ticketDetail.spec.ts',
    title: 'Dialog status button shows the ticket\'s current status',
    description: 'Status combobox label reflects the ticket\'s current status from the API.',
    pre: 'Dialog open for the seed ticket (status: In Progress).',
    data: 'Seed ticket status "In Progress".',
    steps: '1. Read status button text.\n2. Assert it contains "In Progress".',
    expected: 'Status button shows "In Progress".',
    severity: 'Major', priority: 'P1', status: 'Pass', caseType: 'UI and validation',
  },
  {
    id: 'TK0004', feature: 'Ticket Detail', spec: 'e2e/tests/ticketDetail.spec.ts',
    title: 'Opening the status menu reveals all four status options',
    description: 'Status combobox must expose exactly New / In Progress / Resolved / Closed.',
    pre: 'Dialog open.', data: 'None.',
    steps: '1. Click status combobox.\n2. Assert all four options visible.\n3. Assert no extra options.',
    expected: 'Exactly 4 .mantine-Combobox-option entries.',
    severity: 'Major', priority: 'P1', status: 'Pass', caseType: 'UI and validation',
  },
  {
    id: 'TK0005', feature: 'Ticket Detail', spec: 'e2e/tests/ticketDetail.spec.ts',
    title: 'Close (X) button closes the dialog and clears ?selectedId',
    description: 'Clicking the close ActionIcon removes the dialog and clears the URL param.',
    pre: 'Dialog open.', data: 'None.',
    steps: '1. Click close (X).\n2. Assert dialog detached.\n3. Assert ?selectedId is gone.',
    expected: 'Dialog count 0; param removed.',
    severity: 'Minor', priority: 'P2', status: 'Pass', caseType: 'Navigation',
  },
  {
    id: 'TK0006', feature: 'Ticket Detail', spec: 'e2e/tests/ticketDetail.spec.ts',
    title: 'Empty ticket shows "No comments yet" placeholder and comment input',
    description: 'For tickets with zero comments, the dialog renders an empty-state and the Add-a-comment input + Send button.',
    pre: 'Dialog open on a comment-free ticket.', data: 'Seed ticket has 0 comments.',
    steps: '1. Assert "No comments yet" placeholder.\n2. Assert add-a-comment textbox visible.\n3. Assert Send button visible.',
    expected: 'Empty-state + comment-entry UI present.',
    severity: 'Minor', priority: 'P2', status: 'Pass', caseType: 'UI and validation',
  },
  // ---------- New Ticket form (e2e/tests/newTicket.spec.ts) ----------
  {
    id: 'NT0001', feature: 'New Ticket', spec: 'e2e/tests/newTicket.spec.ts',
    title: 'The submit form renders all four required fields',
    description: 'Customer-facing public form must always expose reportedBy / yourName / title / description / Submit.',
    pre: 'Navigate to /<slug>/tickets/new.', data: 'None.',
    steps: '1. Open page.\n2. Assert all four textboxes + Submit visible.',
    expected: 'All five elements visible.',
    severity: 'Critical', priority: 'P0', status: 'Pass', caseType: 'Happy Path',
  },
  {
    id: 'NT0002', feature: 'New Ticket', spec: 'e2e/tests/newTicket.spec.ts',
    title: 'Submitting an empty form shows validation errors on every field',
    description: 'Client-side validation blocks blank submissions on every required field.',
    pre: 'On /<slug>/tickets/new.', data: 'None (empty form).',
    steps: '1. Click Submit.\n2. Assert "Invalid email" + ≥3 "String must contain at least 1 character(s)" errors.\n3. Assert URL unchanged.',
    expected: 'All required-field errors visible; no API call.',
    severity: 'Major', priority: 'P1', status: 'Pass', caseType: 'Validation',
  },
  {
    id: 'NT0003', feature: 'New Ticket', spec: 'e2e/tests/newTicket.spec.ts',
    title: 'Submitting with a malformed reported-by email shows "Invalid email"',
    description: 'Email-format validation rejects malformed input before submit.',
    pre: 'On /<slug>/tickets/new.', data: 'Email: "notanemail" + valid other fields.',
    steps: '1. Fill all fields with malformed email.\n2. Submit.\n3. Assert "Invalid email" error.\n4. Assert URL unchanged.',
    expected: 'Inline email error; no navigation.',
    severity: 'Major', priority: 'P1', status: 'Pass', caseType: 'Validation',
  },
  {
    id: 'NT0004', feature: 'New Ticket', spec: 'e2e/tests/newTicket.spec.ts',
    title: 'Valid submission shows the success toast and lands on the new ticket\'s detail page',
    description: 'Happy path: valid form creates a ticket and redirects to /<slug>/tickets/<id>.',
    pre: 'On /<slug>/tickets/new.',
    data: 'Email "qa-bot@example.com", title "NT0004 e2e probe <timestamp>", body text.',
    steps: '1. Fill all four fields.\n2. Submit.\n3. Assert toast.\n4. Assert URL matches /tickets/<id>.',
    expected: 'Toast + detail-page URL.',
    severity: 'Blocker', priority: 'P0', status: 'Pass', caseType: 'Happy Path',
    notes: 'Creates real ticket each run; non-destructive (no DELETE endpoint).',
  },
  // ---------- Organization Settings (e2e/tests/organizationSettings.spec.ts) ----------
  {
    id: 'OS0001', feature: 'Organization Settings', spec: 'e2e/tests/organizationSettings.spec.ts',
    title: 'Page renders the "Organization members" heading and an "Add member" button',
    description: 'Settings page chrome: heading + primary CTA.',
    pre: 'On /<slug>/settings.', data: 'None.',
    steps: '1. Assert "Organization members" heading.\n2. Assert "Add member" button.',
    expected: 'Both visible.',
    severity: 'Major', priority: 'P1', status: 'Pass', caseType: 'UI and validation',
  },
  {
    id: 'OS0002', feature: 'Organization Settings', spec: 'e2e/tests/organizationSettings.spec.ts',
    title: 'Logged-in user is listed as an Admin in the members roster',
    description: 'The org creator must appear in the members list with role=Admin.',
    pre: 'Test account is the org creator.', data: 'Credentials.valid.email.',
    steps: '1. Assert the user\'s email appears in the roster.\n2. Assert "Admin" text appears in main.',
    expected: 'Email + Admin label visible.',
    severity: 'Major', priority: 'P1', status: 'Pass', caseType: 'Authorization',
  },
  {
    id: 'OS0003', feature: 'Organization Settings', spec: 'e2e/tests/organizationSettings.spec.ts',
    title: '"Add member" opens a dialog with Email + Role inputs and submit button',
    description: 'Add-member modal renders all expected controls.',
    pre: 'On /<slug>/settings.', data: 'None.',
    steps: '1. Click "Add member".\n2. Assert dialog open.\n3. Assert email input, role combobox, submit button visible.\n4. Close.',
    expected: 'Dialog with three controls.',
    severity: 'Minor', priority: 'P2', status: 'Pass', caseType: 'UI and validation',
  },
  {
    id: 'OS0004', feature: 'Organization Settings', spec: 'e2e/tests/organizationSettings.spec.ts',
    title: 'Submitting the Add Member dialog with empty email shows "Invalid email"',
    description: 'Email required — empty submission blocked client-side.',
    pre: 'Add-member dialog open.', data: 'Empty form.',
    steps: '1. Click submit with empty email.\n2. Assert "Invalid email" error inside dialog.\n3. Close.',
    expected: 'Inline error; no invite sent.',
    severity: 'Major', priority: 'P1', status: 'Pass', caseType: 'Validation',
  },
  {
    id: 'OS0005', feature: 'Organization Settings', spec: 'e2e/tests/organizationSettings.spec.ts',
    title: 'Submitting with a malformed email shows "Invalid email" without sending the invite',
    description: 'Email-format check rejects "notanemail" before submitting.',
    pre: 'Add-member dialog open.', data: 'Email "notanemail".',
    steps: '1. Fill malformed email.\n2. Submit.\n3. Assert "Invalid email" error.\n4. Assert dialog still open.',
    expected: 'Dialog stays open; error visible.',
    severity: 'Major', priority: 'P1', status: 'Pass', caseType: 'Validation',
  },
  {
    id: 'OS0006', feature: 'Organization Settings', spec: 'e2e/tests/organizationSettings.spec.ts',
    title: 'Role dropdown exposes both Admin and Member options',
    description: 'Add-member dialog allows choosing Admin or Member.',
    pre: 'Add-member dialog open.', data: 'None.',
    steps: '1. Click Role dropdown.\n2. Assert both options visible.\n3. Close.',
    expected: 'Two role options.',
    severity: 'Minor', priority: 'P2', status: 'Pass', caseType: 'UI and validation',
  },
  {
    id: 'OS0007', feature: 'Organization Settings', spec: 'e2e/tests/organizationSettings.spec.ts',
    title: 'Closing the dialog removes it from the DOM',
    description: 'Dialog close button (X) detaches the modal.',
    pre: 'Add-member dialog open.', data: 'None.',
    steps: '1. Click close (X).\n2. Assert dialog count == 0.',
    expected: 'No dialog in DOM.',
    severity: 'Minor', priority: 'P2', status: 'Pass', caseType: 'Navigation',
  },
  // ---------- Manage Account (e2e/tests/manageAccount.spec.ts) ----------
  {
    id: 'MA0001', feature: 'Manage Account', spec: 'e2e/tests/manageAccount.spec.ts',
    title: 'User details tab renders First name, Last name, Save',
    description: 'Profile edit form must always expose the name fields and save button.',
    pre: 'On /manage-account.', data: 'None.',
    steps: '1. Open page.\n2. Assert First name, Last name, Save visible.',
    expected: 'All three controls visible.',
    severity: 'Minor', priority: 'P2', status: 'Pass', caseType: 'UI and validation',
  },
  {
    id: 'MA0002', feature: 'Manage Account', spec: 'e2e/tests/manageAccount.spec.ts',
    title: 'First name and Last name are pre-filled from the logged-in user\'s profile',
    description: 'Form pre-fills with session data so user can edit in place.',
    pre: 'Signed in.', data: 'session.user.firstName / lastName.',
    steps: '1. Read inputValue() from First name and Last name fields.\n2. Assert both non-empty.',
    expected: 'Both inputs have values.',
    severity: 'Minor', priority: 'P2', status: 'Pass', caseType: 'UI and validation',
  },
  {
    id: 'MA0003', feature: 'Manage Account', spec: 'e2e/tests/manageAccount.spec.ts',
    title: 'The page exposes both "User details" and "Security" tabs',
    description: 'Tab navigation between profile and password sections.',
    pre: 'On /manage-account.', data: 'None.',
    steps: '1. Assert both tabs visible.',
    expected: 'Both tabs present.',
    severity: 'Minor', priority: 'P2', status: 'Pass', caseType: 'Navigation',
  },
  {
    id: 'MA0004', feature: 'Manage Account', spec: 'e2e/tests/manageAccount.spec.ts',
    title: 'Security tab renders Sessions list section heading',
    description: 'Security tab must always show the Sessions section, even when the list is empty (no other devices).',
    pre: 'On /manage-account, Security tab active.', data: 'None.',
    steps: '1. Click Security tab.\n2. Assert "Sessions" heading inside the tabpanel.',
    expected: 'Heading visible.',
    severity: 'Minor', priority: 'P2', status: 'Pass', caseType: 'UI and validation',
    notes: 'Original spec also asserted on "Current" session marker — relaxed because sessions list can be empty on a fresh login.',
  },
  {
    id: 'MA0005', feature: 'Manage Account', spec: 'e2e/tests/manageAccount.spec.ts',
    title: 'Password section exposes Current/New inputs + Sign-out-other-sessions checkbox + Change password button',
    description: 'Security tab\'s password-change form renders all expected controls.',
    pre: 'Security tab active.', data: 'None.',
    steps: '1. Assert sessions heading, password heading, current pw, new pw, checkbox, change pw button.',
    expected: 'All six controls visible.',
    severity: 'Major', priority: 'P1', status: 'Pass', caseType: 'UI and validation',
  },
  {
    id: 'MA0006', feature: 'Manage Account', spec: 'e2e/tests/manageAccount.spec.ts',
    title: 'Clicking Change password with empty fields keeps the user on the page (no destructive call)',
    description: 'Surface check: form does not navigate or invalidate session on empty submit.',
    pre: 'Security tab active.', data: 'Empty form.',
    steps: '1. Click Change password without typing anything.\n2. Assert URL still /manage-account.\n3. Assert current-password input still present.',
    expected: 'No navigation; form persists.',
    severity: 'Major', priority: 'P1', status: 'Pass', caseType: 'Validation',
    notes: 'We deliberately do not exercise a real password change — the test account is shared.',
  },
  {
    id: 'MA0007', feature: 'Manage Account', spec: 'e2e/tests/manageAccount.spec.ts',
    title: 'Switching back to User details tab restores the name form',
    description: 'Tab navigation works bidirectionally.',
    pre: 'Security tab active.', data: 'None.',
    steps: '1. Click User details tab.\n2. Assert First/Last/Save visible.',
    expected: 'User details form restored.',
    severity: 'Minor', priority: 'P2', status: 'Pass', caseType: 'Navigation',
  },
  // ---------- Navigation / session (e2e/tests/navigation.spec.ts) ----------
  {
    id: 'NV0001', feature: 'Navigation', spec: 'e2e/tests/navigation.spec.ts',
    title: 'Session persists across a full page reload',
    description: 'Refreshing the tickets dashboard must NOT log the user out.',
    pre: 'Signed in on /<slug>/tickets.', data: 'None.',
    steps: '1. Reload page.\n2. Assert core chrome visible.\n3. Assert URL still in /<slug>/tickets.',
    expected: 'Page rerenders signed-in.',
    severity: 'Critical', priority: 'P0', status: 'Pass', caseType: 'Session',
  },
  {
    id: 'NV0002', feature: 'Navigation', spec: 'e2e/tests/navigation.spec.ts',
    title: 'Navigating to /onboarding while signed in with an org redirects to /<slug>/tickets',
    description: 'Onboarding page is short-circuited when the user already belongs to an org.',
    pre: 'User has an org.', data: 'None.',
    steps: '1. Navigate to /onboarding.\n2. Wait for redirect.\n3. Assert URL matches /<slug>/tickets.',
    expected: 'Redirect occurs.',
    severity: 'Minor', priority: 'P2', status: 'Pass', caseType: 'Navigation',
  },
  {
    id: 'NV0003', feature: 'Navigation', spec: 'e2e/tests/navigation.spec.ts',
    title: 'User-menu dropdown lists "Manage account" and "Sign out"',
    description: 'Header avatar dropdown shows the two expected options.',
    pre: 'On /<slug>/tickets.', data: 'None.',
    steps: '1. Click avatar.\n2. Assert both menu items visible.\n3. Press Escape.',
    expected: 'Menu shows both items.',
    severity: 'Minor', priority: 'P2', status: 'Pass', caseType: 'Navigation',
  },
  {
    id: 'NV0004', feature: 'Navigation', spec: 'e2e/tests/navigation.spec.ts',
    title: 'Sign out returns user to home, clears session, and blocks protected URLs',
    description: 'Full sign-out flow: UI click → redirect → cookie cleared → protected URL blocked.',
    pre: 'Isolated browser context with a fresh sign-in.',
    data: 'Credentials.valid.{email,password}.',
    steps: '1. New isolated context.\n2. Sign in via UI.\n3. Click avatar > Sign out.\n4. Assert URL is /.\n5. Assert anon header present.\n6. Try protected URL — assert NOT on it.',
    expected: 'Session cleared; protected URLs blocked.',
    severity: 'Critical', priority: 'P0', status: 'Pass', caseType: 'Session',
    notes: 'Runs in isolated context so it does not invalidate the shared storage-state cookie that other specs reuse.',
  },
  {
    id: 'NV0005', feature: 'Navigation', spec: 'e2e/tests/navigation.spec.ts',
    title: 'Org switcher dropdown shows current org and a "Create organization" option',
    description: 'Org switcher lists current org (disabled menu entry) and a create-new option.',
    pre: 'On /<slug>/tickets.', data: 'Current org name.',
    steps: '1. Click org switcher.\n2. Assert "Create organization" option.\n3. Assert current-org name appears.\n4. Press Escape.',
    expected: 'Menu has both entries.',
    severity: 'Minor', priority: 'P2', status: 'Pass', caseType: 'Navigation',
  },
  // ---------- Tickets API — tRPC tickets.create (api/tests/tickets.spec.ts) ----------
  {
    id: 'AT0001', feature: 'Tickets API', spec: E2E_TICKETS_API_SPEC,
    title: 'Valid payload returns the new ticket with status "New"',
    description: 'Anonymous public ticket-submit endpoint creates a ticket scoped to the org named by x-organization.',
    pre: 'Network reachable; org slug known.',
    data: 'qa-exploration-org slug + valid payload.',
    steps: '1. POST tickets.create with valid payload + x-organization header.\n2. Assert 200.\n3. Assert body.status="New", title matches input, id matches /^[a-z0-9]+$/.',
    expected: 'Ticket returned with status New.',
    severity: 'Blocker', priority: 'P0', status: 'Pass', caseType: 'Happy Path',
  },
  {
    id: 'AT0002', feature: 'Tickets API', spec: E2E_TICKETS_API_SPEC,
    title: 'Missing all required fields returns 400 with zod fieldErrors',
    description: 'Schema validation reports every missing field individually.',
    pre: 'Network reachable.', data: '{} inner JSON.',
    steps: '1. POST with empty inner json.\n2. Assert 400 BAD_REQUEST.\n3. Assert fieldErrors contains title, body, reportedBy, authorName.',
    expected: 'All four field paths reported.',
    severity: 'Major', priority: 'P1', status: 'Pass', caseType: 'Validation',
  },
  {
    id: 'AT0003', feature: 'Tickets API', spec: E2E_TICKETS_API_SPEC,
    title: 'Invalid email in reportedBy returns 400 with zod fieldErrors',
    description: 'Email validation surfaces as fieldErrors.reportedBy = ["Invalid email"].',
    pre: 'Network reachable.', data: 'reportedBy="notanemail" + other valid fields.',
    steps: '1. POST.\n2. Assert 400.\n3. Assert fieldErrors.reportedBy contains "Invalid email".',
    expected: 'Email error reported in fieldErrors.',
    severity: 'Major', priority: 'P1', status: 'Pass', caseType: 'Validation',
  },
  {
    id: 'AT0004', feature: 'Tickets API', spec: E2E_TICKETS_API_SPEC,
    title: 'Empty inner JSON returns 400 with zod formErrors "Required"',
    description: 'Missing the tRPC inner payload entirely surfaces as formErrors (not fieldErrors).',
    pre: 'Network reachable.', data: '{} outer JSON (no "0" key).',
    steps: '1. POST with completely empty body.\n2. Assert 400.\n3. Assert formErrors=["Required"].',
    expected: 'formErrors path set.',
    severity: 'Minor', priority: 'P2', status: 'Pass', caseType: 'Validation',
  },
  {
    id: 'AT0005', feature: 'Tickets API', spec: E2E_TICKETS_API_SPEC,
    title: 'Missing x-organization header returns 403 FORBIDDEN',
    description: 'The endpoint scopes to an org via the header; without it the request is forbidden.',
    pre: 'Network reachable.', data: 'Valid payload, NO x-organization header.',
    steps: '1. POST without x-organization.\n2. Assert 403.\n3. Assert body.data.code="FORBIDDEN".',
    expected: 'FORBIDDEN response.',
    severity: 'Major', priority: 'P1', status: 'Pass', caseType: 'Authorization',
  },
  {
    id: 'AT0006', feature: 'Tickets API', spec: E2E_TICKETS_API_SPEC,
    title: 'Unknown organization slug returns 403 FORBIDDEN',
    description: 'Unknown slug also returns FORBIDDEN (no enumeration leak).',
    pre: 'Network reachable.', data: 'x-organization="nonexistent-org-9921".',
    steps: '1. POST with unknown slug.\n2. Assert 403.\n3. Assert body.data.code="FORBIDDEN".',
    expected: 'FORBIDDEN response.',
    severity: 'Major', priority: 'P1', status: 'Pass', caseType: 'Authorization',
  },
];

const workbook = new ExcelJS.Workbook();
workbook.creator = 'AutoQA';
workbook.created = new Date();

// Split rows by suite based on their `spec` field (or the default for sign-in
// rows that omit it). Anything under `e2e/tests/` goes to the `e2e` sheet;
// anything under `api/tests/` goes to the `api` sheet.
const e2eRows = rows.filter((r) => (r.spec ?? E2E_SPEC).startsWith('e2e/tests/'));
const apiRows = rows.filter((r) => (r.spec ?? '').startsWith('api/tests/'));

function buildSheet(name, sheetRows, defaultSpec) {
  const sheet = workbook.addWorksheet(name);
  sheet.columns = HEADERS.map((h) => ({ header: h, width: Math.max(h.length + 2, 16) }));
  sheet.getRow(1).font = { bold: true };
  sheet.getColumn(7).width = 60; // Steps
  sheet.getColumn(8).width = 50; // Expected Result
  sheet.getColumn(6).width = 40; // Test Data
  sheet.getColumn(4).width = 50; // Description
  for (const r of sheetRows) {
    sheet.addRow([
      r.id, r.feature, r.title, r.description, r.pre, r.data, r.steps,
      r.expected, r.severity, r.priority, r.status, r.caseType,
      TODAY, 'AutoQA', r.spec ?? defaultSpec, r.notes ?? '',
    ]);
  }
  sheet.eachRow((row) => row.alignment = { vertical: 'top', wrapText: true });
  return sheet;
}

buildSheet('e2e', e2eRows, E2E_SPEC);
buildSheet('api', apiRows, API_SPEC);

const outPath = path.join(__dirname, 'TEST-CASES.xlsx');
await workbook.xlsx.writeFile(outPath);
console.log(`Wrote ${outPath} (${e2eRows.length} E2E + ${apiRows.length} API = ${rows.length} rows).`);
